service: psrproj

plugins:
  - aws-amplify-serverless-plugin
  - serverless-s3-sync

custom:
  stage: beta
  FileUploadBucketName: psr-user-file-bucket-011899
  ReactAppBucketName: psr-proj-react-0118999
  amplify:
    - filename: src/aws-exports.js
      type: javascript
      appClient: CognitoUserPoolClient
  s3Sync:
    - bucketName: ${{self:custom.ReactAppBucketName}}
      localDir: build/

package:
  exclude:
    - amplify/**
    - public/**
    - src/**
    - node_modules/**

provider:
  name: aws
  runtime: nodejs12.x
  stage: beta
  region: eu-west-1
  variableSyntax: "\\${{([\\s\\S]+?)}}"

functions:
  hello:
    handler: handlers/handler.hello
    events:
      - http:
          path: /test
          method: any
          cors: true
          authorizer: aws_iam

resources:
  - ${{file(resources/cognito-user-pool.yml)}}
  - ${{file(resources/cognito-identity-pool.yml)}}
  - ${{file(resources/s3-bucket-userfile.yml)}}
  - ${{file(resources/s3-bucket-react.yml)}}
