Resources:
  UserFileBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${{self:custom.FileUploadBucketName}}
      # Set the CORS policy
      CorsConfiguration:
        CorsRules:
          -
            AllowedOrigins:
              - '*'
            AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
              - HEAD
            ExposedHeaders:
              - x-amz-server-side-encryption
              - x-amz-request-id
              - x-amz-id-2
            MaxAge: 3000

Outputs:
  UserFileBucketName:
    Value:
      Ref: UserFileBucket

