Resources:
  UserFileBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: psr-user-file-bucket-011899
      # Set the CORS policy
      CorsConfiguration:
        CorsRules:
          -
            AllowedOrigins:
              - '*'
            AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
              - HEAD
            MaxAge: 3000

Outputs:
  UserFileBucketName:
    Value:
      Ref: UserFileBucket

