Resources:
  UserFileBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${self:custom.FileUploadBucketName}
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: 
              - '*'
            AllowedMethods: 
              - HEAD
              - GET
              - PUT
              - POST
              - DELETE
            AllowedOrigins: 
              - '*'
            ExposedHeaders:
              - x-amz-server-side-encryption
              - x-amz-request-id
              - x-amz-id-2
            MaxAge: 3000
