// WARNING: DO NOT EDIT.  This file is automatically generated
// Written by aws-amplify-serverless-plugin/1.4.1 on 2020-09-27T11:00:52.486Z

const awsmobile = {
    aws_cloud_logic_custom: [
        {
            endpoint: 'https://zhyy9rwbib.execute-api.eu-west-1.amazonaws.com/beta',
            name: 'ApiGatewayRestApi',
            region: 'eu-west-1'
        }
    ],
    aws_cognito_identity_pool_id: 'eu-west-1:c7efb145-b7e3-4037-a199-ec36e77c0815',
    aws_cognito_region: 'eu-west-1',
    aws_project_region: 'eu-west-1',
    aws_user_files_s3_bucket: 'psr-proj-react-0118999',
    aws_user_files_s3_bucket_region: 'eu-west-1',
    aws_user_pools_id: 'eu-west-1_Sd63ofZmY',
    aws_user_pools_web_client_id: '673mrm64ebu3if8b0ae775g1bj'
};

export default awsmobile;
