// WARNING: DO NOT EDIT.  This file is automatically generated
// Written by aws-amplify-serverless-plugin/1.4.1 on 2020-09-27T12:07:24.385Z

const awsmobile = {
    aws_cloud_logic_custom: [
        {
            endpoint: 'https://07kegx9n9d.execute-api.eu-west-1.amazonaws.com/beta',
            name: 'ApiGatewayRestApi',
            region: 'eu-west-1'
        }
    ],
    aws_cognito_identity_pool_id: 'eu-west-1:83ecdb04-34e8-48b5-9c90-5070744499c5',
    aws_cognito_region: 'eu-west-1',
    aws_project_region: 'eu-west-1',
    aws_user_files_s3_bucket: 'psr-proj-react-0118999',
    aws_user_files_s3_bucket_region: 'eu-west-1',
    aws_user_pools_id: 'eu-west-1_yfiMk61dY',
    aws_user_pools_web_client_id: '46akh1up0gopppcaj7i9irvrjj'
};

export default awsmobile;
